### ISSUE TITLE
Convert pdf to jpeg

### ISSUE THREAD

**Issue by shaair** [imazen/resizer-web#13]
Is it possible to convert pdf to jpeg using this library? and it will be portable to Core CLR.

**Comment by nathanaeljones** [comment]
This is the wrong repository for this question. See https://github.com/imazen/resizer

There are currently only a handful of libraries that have been ported to Core CLR. We are working on a cross-platform imaging engine to make this a possibility. 

See:
http://imageresizing.net/docs/v4/plugins/pdfrenderer
http://imageresizing.net/docs/v4/plugins/pdfiumrenderer
